### ISSUE TITLE
Calling API Method - Contact

### ISSUE THREAD

**Issue by bryan13h** [mccurrymitchell3/hemaa-membership-checker#3]
### **Story/Task Details**

- [x] We are going to call the Contact method in TidyHQ to find the user ID

- [x] Link the User ID with the email of the member

- [x] We are going use python as main programming language 

### Acceptance Scenarios
Given: The contact method is called
When: python code calls the method
Then:  we are given the of User ID
### Done Done Criteria
The backend should call the Contact API method and call the Member API method and link the User ID with the email of the member.
